# JOINING AND SPLIT


# CONCATENATE Function

In [26]:
# JOIN ARRAY - putting contents of two or more array in single array

import numpy as np

var = np.array([1,2,3])

var1 = np.array([4,5,6])

var2 = np.concatenate((var,var1))  # Here we concatenate two arrays 

print(var2)

[1 2 3 4 5 6]


In [44]:
var1 = np.array([[1,2],[3,4]])

var2 = np.array([[5,6],[7,8]])

var3 = np.concatenate((var1,var2),axis = 0)  # Here we concatenate two arrays on 0 axis column wise 
var4 = np.concatenate((var1,var2),axis = 1)  # Here we concatenate two arrays on 1 axis row  wise 

print("On axis 0 : ", var3)
print()
print("On axis 1 : ", var4)
print()

On axis 0 :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]

On axis 1 :  [[1 2 5 6]
 [3 4 7 8]]



# STACK Function

In [54]:
# It is also used for concatenate two arrays


num = np.array([1,2,3])

num1 = np.array([4,5,6])

num2 = np.vstack((num,num1))
num3 = np.hstack((num,num1))
num4 = np.dstack((num,num1))
print(" v - Vertical Stack (COLUMN WISE ): \n" , num2)
print()
print(" h - Horizontal Stack (ROW WISE ): \n" , num3)
print()
print(" d - Height Stack (HEIGHT WISE ): \n" , num4)
print()





 v - Vertical Stack (COLUMN WISE ): 
 [[1 2 3]
 [4 5 6]]

 h - Horizontal Stack (ROW WISE ): 
 [1 2 3 4 5 6]

 d - Height Stack (HEIGHT WISE ): 
 [[[1 4]
  [2 5]
  [3 6]]]



# SPLIT Function

In [56]:
n = np.array([1,2,3,4])
print(n)
print()
n1 = np.array_split(n,2) # Here we splited array it 2 equal parts
n2 = np.array_split(n,3) # In 3 parts 
print(n1)
print()
print(n2)



[1 2 3 4]

[array([1, 2]), array([3, 4])]

[array([1, 2]), array([3]), array([4])]


In [65]:
# Two dimentional Spliting

n3 = np.array([[1,2],[3,4]])
print(np.array_split(n3,2))
print()
print(np.array_split(n3,3,axis = 1))  # According to axis

[array([[1, 2]]), array([[3, 4]])]

[array([[1],
       [3]]), array([[2],
       [4]]), array([], shape=(2, 0), dtype=int32)]
