# Shuffle Function

In [7]:
import numpy as np

var = np.array([1,2,3,4,5])
v = np.random.shuffle(var)      # Here it suffles the data in a random order
print(var)

[2 3 4 1 5]


# Unique Function

In [22]:
var1 = np.array([1,2,3,4,3,2])   # Here it returns the single copy of the repeated element
print(np.unique(var1))


[1 2 3 4]


# Resize Function

In [18]:
var2 = np.array([1,2,3,4,5,6])
print(np.resize(var2,(2,3)))      # Using this function we can convert one dimentional array into multidimentional array 
                                  # In which we can specify the number of rows and column

[[1 2 3]
 [4 5 6]]


# Flatten and Ravel

In [31]:
# Used to convert two dimentional array into one dimentional array

var3 = np.array([1,2,3,4,5,6])
v = np.resize(var2,(2,3))
print("Two Dimentional : \n", v)
print()
print("One Dimentional : \n", v.flatten())     # Flatten
print()                                         # Here we converted two dimentional array into one dimentional array
print("One Dimentional : \n", v.ravel())       # Ravel

Two Dimentional : 
 [[1 2 3]
 [4 5 6]]

One Dimentional : 
 [1 2 3 4 5 6]

One Dimentional : 
 [1 2 3 4 5 6]
