# Insert

In [4]:
import numpy as np

var = np.array([1,2,3,4,5])
v = np.insert(var,3,100) # Function , variable name , location , value to be inserted
print(v)
print()
v1 = np.insert(var,(1,2),(2,4))
print(v1)

[  1   2   3 100   4   5]

[1 2 2 4 3 4 5]


# Delete 

In [6]:
var1 = np.array([1,2,3,4,5])
n = np.delete(var1,2)       # Function , Variable name , Location
print(var1)
print(n)

[1 2 3 4 5]
[1 2 4 5]
