# Matrix

In [6]:
import numpy as np

# Multiplication of Martix 

var1 = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[1,2],[3,4]])
print(var1.dot(var2))
print()
print(var1 + var2)
print()
print(var1 / var2)

[[ 7 10]
 [15 22]]

[[2 4]
 [6 8]]

[[1. 1.]
 [1. 1.]]


# Functions in Marix

# 1.Transpose

In [7]:
var3 = np.matrix([[1,2],[3,4]])
print(np.transpose(var3))

[[1 3]
 [2 4]]


# 2.Swapaxes

In [8]:
var4 = np.matrix([[1,2],[3,4]])
print(np.swapaxes(var4,0,1))    # 0 and 1 are axis that are swaped


[[1 3]
 [2 4]]


# 3.Inverse

In [15]:
 var5 = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(var5))

[[-2.   1. ]
 [ 1.5 -0.5]]


# 4.Power

In [14]:
var6 = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(var6,0))
print()
print(np.linalg.matrix_power(var6,2))
print()
print(np.linalg.matrix_power(var6,-2))
print()

[[1 0]
 [0 1]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



# 5.Diterminant

In [23]:
var7 = np.matrix([[1,2,3],[3,4,5],[1,7,8]])
print(np.linalg.det(var7))

10.000000000000002
