#  Random Functions in python


# 1. rand function

In [4]:
#Here this function generates random numbers between 0 to 1

import numpy as np

a = np.random.rand(5) # Here it states the number of elements generated between 0 and 1
print(a)


[0.10157952 0.03576618 0.71055311 0.04957173 0.2469863 ]


# 2. randn Function

In [11]:
# This Function generates random values close to zero 
#(may be positive or negative)

num = np.random.randn(4)  # States how many number to be generated
print(num)

[-1.05376454  0.32008866 -1.41180158  0.70118909]


# 3. ranf Function

In [14]:
# This function genarates random number including 0 but less than 1
var = np.random.ranf(4)

print(var)


[0.02028853 0.62312803 0.3959864  0.55826637]


# 4. randint Function

In [19]:
# Genarates random number between specified range 

a = 0
b = 5
c = 4
var1 = np.random.randint(a,b,c)
#  Here it range of function 
# a to b is range and c is how many 
# numbers to be generated between that range
print(var1)

[0 3 1 2]
