# Data Types 

In [11]:
import numpy as np

var = np.array([1,2,2,3])
print("Data type:",var.dtype)
print()

var1 = np.array(['a','b','c'])
print("Data type :",var1.dtype)
print()
    
var2 = np.array([1.2,4.3,5.4])
print("Data type :", var2.dtype)
print()


var3 = np.array(['f','a','g',1.2,4.3,5.4])
print("Data type :", var3.dtype)
print()


Data type: int32

Data type : <U1

Data type : float64

Data type : <U32



# Data Type Conversion

In [4]:
import numpy as np
n = np.array([1,2,2,4,5,6])
print(n)
print(n.dtype) # This line is used for identifying Data type of variable 
print()

# Converting one data type in another 
# Method 1: 

num = np.array(n, dtype = "f")  
print(num)
print(num.dtype)
print()

# Method 2: 
num2 = num.astype(float)
print(num2)
print(num2.dtype)

[1 2 2 4 5 6]
int32

[1. 2. 2. 4. 5. 6.]
float32

[1. 2. 2. 4. 5. 6.]
float64
