# Arithmetic Operations 

#  On One Dimention Array

In [1]:
import numpy as np

n = np.array([1,2,3,4,5])
num = n + 5               # Here we are adding 5 to each number in array
print(num)

[ 6  7  8  9 10]


In [ ]:
n1 = np.array([1,2,3])
n2 = np.array([1,2,3]) 

# Here we are adding array element with other array element 

print("Adding Methods")
print(n1 + n2)
print()

n3 = np.array([1,2,3])
n4 = np.array([1,2,3])

# We can also use pre-built in function to add elements

# Addition
print("Addition")
num2 = np.add(n3,n4)   
print(num2)
print()

# Similarly we can perform other arithmetic operation such as 

# SUBTRACTION
print("Subtraction ")
num2 = np.subtract(n3,n4)   
print(num2)
print()

# MULTIPLICATION

print("Multiplication ")

num2 = np.multiply(n3,n4)   
print(num2)
print()

# DIVISION

print("Divison ")
num2 = np.divide(n3,n4)   
print(num2)
print()

# MOD

print("Mod ")
num2 = np.mod(n3,n4)   
print(num2)
print()

# Power


print("Power ")
num2 = np.power(n3,2)   
print(num2)
print()

# Reciprocal

print("Reciprocal ")
num2 = np.reciprocal(n4)   
print(num2)
print()

#  On Two Dimention Array

In [31]:
no = np.array([[1,2,3],[1,2,3]])
no1 = np.array([[2,4,6],[2,4,6]])
result = np.add(no,no1)
print(result)

# SUBTRACTION
print("Subtraction ")
result1 = np.subtract(no,no1)   
print(result1)
print()

# MULTIPLICATION

print("Multiplication ")

result2 = np.multiply(no,no1)   
print(result2)
print()

# DIVISION

print("Divison ")
result3 = np.divide(no,no1)   
print(result3)
print()

# MOD

print("Mod ")
result4 = np.mod(no,no1)   
print(result4)
print()

# Power


print("Power ")
result5 = np.power(no,2)   
print(result5)
print()

# Reciprocal

print("Reciprocal ")
result6 = np.reciprocal(no,no1)   
print(result6)
print()

[[3 6 9]
 [3 6 9]]
Subtraction 
[[-1 -2 -3]
 [-1 -2 -3]]

Multiplication 
[[ 2  8 18]
 [ 2  8 18]]

Divison 
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]

Mod 
[[1 2 3]
 [1 2 3]]

Power 
[[1 4 9]
 [1 4 9]]

Reciprocal 
[[1 0 0]
 [1 0 0]]

