# SHAPE

In [1]:
import numpy as np

arr = np.array([1,2,3,3,4,5],ndmin = 2)
print(arr)
print()
print(arr.shape)  

# Here shape represents the number of rows and column in a matrix 

var = arr.reshape(3,2)

# Here reshape is used to modify the number of ROWS and COLUMN in a matrix 
print(var)


[[1 2 3 3 4 5]]

(1, 6)
[[1 2]
 [3 3]
 [4 5]]


In [12]:
import numpy as np 

one_d = np.array([1,2,3,4,5,6,7,8])
print("One Dimention :\n",one_d)
print()

var1 = one_d.reshape(2,2,2) # 2 * 2 matrix with element 2 in it i.e column , row and number of elements(2,2,2)

print("After Reshaping : \n")
print(var1)

print()


var2 = var1.reshape(-1)
print("Again in Original form :\n",var2)
print()

One Dimention :
 [1 2 3 4 5 6 7 8]

After Reshaping : 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Again in Original form :
 [1 2 3 4 5 6 7 8]

