In [8]:
# import numpy as  np

var1 = np.array([1,2,3])
print("1*3 matrix")
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print("3*1 matrix")
print(var2.shape)
print()
print(var2)
print()
print("Addition is")
var3 = var1 + var2
print(var3)
print()


#Condition for broadcasting 

# 1. Atleast one should be same according to dimentions
#2. should have same number of elements

1*3 matrix
(3,)

[1 2 3]

3*1 matrix
(3, 1)

[[1]
 [2]
 [3]]

Addition is
[[2 3 4]
 [3 4 5]
 [4 5 6]]

