In [1]:
import numpy as np

var = np.array([1,2,3,4])
print(var)   # Simple display 
print()

for i in var:  # Iteration Display 
     print(i)

[1 2 3 4]

1
2
3
4


In [14]:
# Two dimentional array Display
print("Two dimentional")
var1 = np.array([[1,2,3],[4,5,6]])

for i in var1:
    for j in i:
        print(i)
print()
# Three Dimentional
print("Three Dimentional")

var2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

    for i in var2:
        for j in i :
            for k in i:
                print(k)

Two dimentional
[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]

Three Dimentional
[1 2 3]
[4 5 6]
[7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]


# nditer Function

In [27]:
# Instead using multiple for loop we can use 'nditer' function

num3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(num3):
    print("Elements are : ", i)
print()
print()

num4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(num4,flags = ['buffered'],op_dtypes = ["S"]):    # Here it converts the data in var into string data type
                                                                    # Buffer - data converted is stored in here 
                                                                    # op_dtype - to which data type to be changed
    print("Elements are : ", i)
    



Elements are :  1
Elements are :  2
Elements are :  3
Elements are :  4
Elements are :  5
Elements are :  6
Elements are :  7
Elements are :  8
Elements are :  9
Elements are :  10


Elements are :  b'1'
Elements are :  b'2'
Elements are :  b'3'
Elements are :  b'4'
Elements are :  b'5'
Elements are :  b'6'
Elements are :  b'7'
Elements are :  b'8'
Elements are :  b'9'
Elements are :  b'10'


# ndenumerate Function

In [35]:
# It gives data plus indexing 

var2 = np.array([1,2,233,3])
for i in np.ndenumerate(var2):
    print(i)

((0,), 1)
((1,), 2)
((2,), 233)
((3,), 3)
